### Busca todas as turmas
GET http://localhost:3003/classrooms

### busca estudantes
GET http://localhost:3003/students

### criar turma
POST http://localhost:3003/classrooms
    Content-Type: application/json

{
    "name": "test",
    "modules": "6"
}

### criar estudantes
POST http://localhost:3003/students
    Content-Type: application/json

{
    "name": "Pâmela",
"email": "pamelamaiara1998@gmail.com",
"birthdate": "1998/10/15",
"classroomId": "101"
}

### auteração de turma

### auteração de estudante
